dist: trusty

# Travis builds are slower using sudo: false (the container-based
# infrastructure) as of March 2017; see
# https://github.com/coq/coq/pull/467 for some discussion.
sudo: required

# Until Ocaml becomes a language, we set a known one.
language: c

cache:
  directories:
  - $HOME/.opam

before_cache:
  - rm -rf ~/.opam/log/

env:
  global:
  - NJOBS=2
  - COMPILER="4.07.0"
  - DUNE_VER=".1.2.1"
  - FINDLIB_VER=".1.8.0"
  - LABLGTK="lablgtk.2.18.6 conf-gtksourceview.2"
  - NATIVE_COMP="yes"
  - COQ_DEST="-local"
  - MAIN_TARGET="world"

matrix:
  include:
    - env:
      - TEST_TARGET="lint"
      install: []
      before_script: []
      addons:
      apt:
        sources: []
        packages: []
      script:
        - dev/lint-repository.sh

    - os: osx
      env:
      - TEST_TARGET="test-suite"
      - NATIVE_COMP="no"
      - COQ_DEST="-local"
      - EXTRA_OPAM="ounit"
      before_install:
      - brew update
      - brew unlink python
      - brew install gnu-time
      # only way to continue using OPAM 1.2
      - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/d156edeeed7291f4bc1e08620b331bbd05d52b78/Formula/opam.rb
      - opam init -j "$NJOBS" --compiler="$COMPILER" -n -y
      - opam switch "$COMPILER" && opam update
      - eval $(opam config env)
      - opam config list
      - opam install -j "$NJOBS" -y num ocamlfind${FINDLIB_VER} dune${DUNE_VER} ${EXTRA_OPAM}
      - opam list

before_install:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then echo "Tested commit (followed by parent commits):"; git log -1; for commit in `git log -1 --format="%P"`; do echo; git log -1 $commit; done; fi

script:

- set -e
- echo 'Testing make clean...' && echo -en 'travis_fold:start:coq.clean\\r'
- make clean # ensure that `make clean` works on a fresh clone
- echo -en 'travis_fold:end:coq.clean\\r'

- echo 'Configuring Coq...' && echo -en 'travis_fold:start:coq.config\\r'
- ./configure $COQ_DEST -warn-error yes -native-compiler $NATIVE_COMP $EXTRA_CONF
- echo -en 'travis_fold:end:coq.config\\r'

- echo 'Building Coq...' && echo -en 'travis_fold:start:coq.build\\r'
- make -j $NJOBS $MAIN_TARGET
- echo -en 'travis_fold:end:coq.build\\r'

- echo 'Running tests...' && echo -en 'travis_fold:start:coq.test\\r'
- if [ -n "$TEST_TARGET" ]; then $TW make -j $NJOBS $TEST_TARGET; fi
- echo -en 'travis_fold:end:coq.test\\r'
- set +e

# Testing Gitter webhook
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3cdabdec318214c7cd63
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
